print("enter the price :")
price = float(input())
print("enter the discount % :")
discount = float(input())
print("enter the vat % :")
vat = float(input())
base = price * (1-discount/100)
vat_amount  = base * (vat/100)
total = base + vat_amount
print("the price after discount :",f"{base:.2f}")
print("the vat :", f"{vat_amount:.2f}")
print("total :", f"{total:.2f}")